version: '2'
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  # appears to cause problem for hooks, which do have similar code structures with
  # different variables
  similar-code:
    enabled: true
  identical-code:
    enabled: true
exclude_patterns:
  # common rule breakers
  - '**/config/*'
  - '**/test/*'
  - '**/seeds/*'
  - '**/migrations/*'
  - '**/aurelia_project/*'
  # models have long methods that create objects in-place
  - '**/*.model.*'
  # service/hook files have identical code blocks
  - '**/*.hooks.*'
  # services all have identical code for most of the content
  - '**/*.service.*'
  # hooks have similar structures
  - '**/hooks/*'
  - '**/*.config.js'
  - '**/webpack.config.babel.js'
