language: node_js
node_js:
  - '8'
  - '10'
  - '12'
cache:
  yarn: true
  directories:
    - 'node_modules'
env:
  - NODE_ENV=development

before_script:
  # bootstrap repo
  - yarn bootstrap
  # setup codeclimate coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  # setup for codecov
  - yarn global add codecov
  # setup the database (sqlite)
  - yarn migrate
  - yarn seed

after_script:
  # send coverage data to codeclimate
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.backend.json packages/backend/coverage/lcov.info # Format backend coverage
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.frontend.json packages/frontend/coverage/lcov.info # Format frontend coverage
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2
  - ./cc-test-reporter upload-coverage
  # send coverage data to codecov
  - codecov
