language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - 'node_modules'
env:
  - NODE_ENV=development

before_script:
  # setup codeclimate coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  # setup the database (sqlite)
  - lerna run migrate-latest --scope=kennelog-backend
after_script:
  # send coverage data to codeclimate
  - ./cc-test-reporter after-build
